[2024-05-14T03:39:41.546+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T03:39:41.598+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.four_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:41.614+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.four_task manual__2024-05-14T03:39:29.168944+00:00 [queued]>
[2024-05-14T03:39:41.617+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 5
[2024-05-14T03:39:41.727+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): four_task> on 2024-05-14 03:39:29.168944+00:00
[2024-05-14T03:39:41.751+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T03:39:41.759+0000] {standard_task_runner.py:63} INFO - Started process 83 to run task
[2024-05-14T03:39:41.752+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'TAREAS_EN_PARALELO_Y_EN_SERIE', 'four_task', 'manual__2024-05-14T03:39:29.168944+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/paralelo_serie_dag.py', '--cfg-path', '/tmp/tmp620c0n5j']
[2024-05-14T03:39:41.763+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask four_task
[2024-05-14T03:39:41.871+0000] {task_command.py:426} INFO - Running <TaskInstance: TAREAS_EN_PARALELO_Y_EN_SERIE.four_task manual__2024-05-14T03:39:29.168944+00:00 [running]> on host 33978f229c7f
[2024-05-14T03:39:42.029+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='TAREAS_EN_PARALELO_Y_EN_SERIE' AIRFLOW_CTX_TASK_ID='four_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T03:39:29.168944+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T03:39:29.168944+00:00'
[2024-05-14T03:39:42.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T03:39:42.036+0000] {logging_mixin.py:188} INFO - Ejecutando four_task
[2024-05-14T03:39:42.036+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T03:39:42.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T03:39:42.049+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=TAREAS_EN_PARALELO_Y_EN_SERIE, task_id=four_task, execution_date=20240514T033929, start_date=20240514T033941, end_date=20240514T033942
[2024-05-14T03:39:42.095+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T03:39:42.128+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T03:39:42.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
